### ISSUE TITLE
java.lang.AbstractMethodError: org.datasyslab.geospark.formatMapper.PointFormatMapper.call with geospark-0.8.2-spark-1.x.jar

### ISSUE THREAD

**Issue by leiguo3** [DataSystemsLab/GeoSpark#129]
The implementation of the "call" function in PointFormatMapper.java of GeoSpark-0.8.2-spark-1.x is not compatible with the declaration of that function in spark 2.2.0.

The implementation in GeoSpark-0.8.2-spark-1.x:
    @Override
    public List<Object> call(Iterator<String> stringIterator) throws Exception {

The declaration of "call" function in spark 2.2.0:
https://spark.apache.org/docs/2.2.0/api/java/org/apache/spark/api/java/function/FlatMapFunction.html

The exception when usring GeoSpark-0.8.2-spark-1.x with spark 2.2.0:

Caused by: java.lang.AbstractMethodError: org.datasyslab.geospark.formatMapper.PointFormatMapper.call(Ljava/lang/Object;)Ljava/util/Iterator;
  at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:153)
  at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:153)
  at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:797)
  at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:797)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
  at org.apache.spark.rdd.RDD$$anonfun$8.apply(RDD.scala:336)
  at org.apache.spark.rdd.RDD$$anonfun$8.apply(RDD.scala:334)
  at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1038)
  at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1029)
  at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:969)
  at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1029)
  at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:760)
  at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:334)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:285)
  at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
  at org.apache.spark.scheduler.Task.run(Task.scala:108)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)

**Comment by leiguo3** [comment]
Noticed that this jar should be used with spark 1.x version. Not a problem, close it.
