### ISSUE TITLE
DistanceJoin Issue with datasets

### ISSUE THREAD

**Issue by khajaasmath786** [DataSystemsLab/GeoSpark#163]
Job aborted due to stage failure: Task 48 in stage 23.0 failed 4 times, most recent failure: Lost task 48.3 in stage 23.0 (TID 18618, brksvl254.brk.navistar.com, executor 46): java.lang.NullPointerException +details
Job aborted due to stage failure: Task 48 in stage 23.0 failed 4 times, most recent failure: Lost task 48.3 in stage 23.0 (TID 18618, brksvl254.brk.navistar.com, executor 46): java.lang.NullPointerException
	at org.datasyslab.geosparksql.utils.Adapter$$anonfun$toRdd$1.apply(Adapter.scala:46)
	at org.datasyslab.geosparksql.utils.Adapter$$anonfun$toRdd$1.apply(Adapter.scala:46)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:214)
	at scala.collection.AbstractIterator.aggregate(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$aggregate$1$$anonfun$22.apply(RDD.scala:1112)
	at org.apache.spark.rdd.RDD$$anonfun$aggregate$1$$anonfun$22.apply(RDD.scala:1112)
	at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:1980)
	at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:1980)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:

**Comment by jiayuasu** [comment]
@khajaasmath786 Any updates?
