### ISSUE TITLE
scala.MatchError using GeoSparkSql on ThriftServer2

### ISSUE THREAD

**Issue by sasoria** [DataSystemsLab/GeoSpark#198]
Running geosparksql on HiveThriftServer2 gives the following error in beeline:

```
Error: scala.MatchError: org.apache.spark.sql.geosparksql.UDT.GeometryUDT@18baee88 (of class org.apache.spark.sql.geosparksql.UDT.GeometryUDT) (state=,code=0)
```

## Steps to reproduce

* set singleSession to true in SparkConf:
```java
.set("spark.sql.hive.thriftServer.singleSession", "true")
```
* register geosparksql functions to SqlContext with `GeoSparkSQLRegistrator`
* read testpoint.csv
* create temporary view:
```java
Dataset<Row> pointDf = spark.sql("select ST_Point(cast(pointtable._c0 as Decimal(24,20)),cast(pointtable._c1 as Decimal(24,20)), \"myPointId\") as pointshape from pointtable");
pointDf.createOrReplaceTempView("pointdf");
```
* start HiveThriftServer2:
```java
HiveThriftServer2.startwithContext(spark.sqlContext());
```
* connect to the server with beeline
* run geosparksql queries in beeline on the registered view:

```sql
select * from pointdf;
select * from pointdf where ST_Contains(ST_PolygonFromEnvelope(1.0,100.0,1000.0,1100.0), pointdf.pointshape));
```

Both queries results in the error described above. However when I run them directly as a spark job, as in the TemplateProject, it runs fine - i.e:
```java
Dataset<Row> resultDf = spark.sql("select * from pointdf where ST_Contains(ST_PolygonFromEnvelope(1.0,100.0,1000.0,1100.0), pointdf.pointshape)");
resultDf.createOrReplaceTempView("resultdf");
resultDf.show();
```

Java stack trace when querying from beeline:

```
java.lang.RuntimeException: scala.MatchError: org.apache.spark.sql.geosparksql.UDT.GeometryUDT@18baee88 (of class org.apache.spark.sql.geosparksql.UDT.GeometryUDT)
	at org.apache.hive.service.cli.session.HiveSessionProxy.invoke(HiveSessionProxy.java:83)
	at org.apache.hive.service.cli.session.HiveSessionProxy.access$000(HiveSessionProxy.java:36)
	at org.apache.hive.service.cli.session.HiveSessionProxy$1.run(HiveSessionProxy.java:63)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1692)
	at org.apache.hive.service.cli.session.HiveSessionProxy.invoke(HiveSessionProxy.java:59)
	at com.sun.proxy.$Proxy29.fetchResults(Unknown Source)
	at org.apache.hive.service.cli.CLIService.fetchResults(CLIService.java:455)
	at org.apache.hive.service.cli.thrift.ThriftCLIService.FetchResults(ThriftCLIService.java:621)
	at org.apache.hive.service.cli.thrift.TCLIService$Processor$FetchResults.getResult(TCLIService.java:1553)
	at org.apache.hive.service.cli.thrift.TCLIService$Processor$FetchResults.getResult(TCLIService.java:1538)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39)
	at org.apache.hive.service.auth.TSetIpAddressProcessor.process(TSetIpAddressProcessor.java:53)
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: scala.MatchError: org.apache.spark.sql.geosparksql.UDT.GeometryUDT@18baee88 (of class org.apache.spark.sql.geosparksql.UDT.GeometryUDT)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.addNonNullColumnValue(SparkExecuteStatementOperation.scala:80)
	at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.getNextRowSet(SparkExecuteStatementOperation.scala:144)
	at org.apache.hive.service.cli.operation.OperationManager.getOperationNextRowSet(OperationManager.java:220)
	at org.apache.hive.service.cli.session.HiveSessionImpl.fetchResults(HiveSessionImpl.java:685)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hive.service.cli.session.HiveSessionProxy.invoke(HiveSessionProxy.java:78)
	... 18 more
```

**Comment by sasoria** [comment]
It look like this was solved in [SPARK-21396](https://github.com/apache/spark/pull/20385) and should be working in Apache Spark 2.3. There was a missing case for User Defined Types:
```scala
case udt: UserDefinedType[_] =>
        to += from.get(ordinal).toString
```

**Comment by jiayuasu** [comment]
@sasoria Can you please try GeoSparkSQL with Spark 2.3? I am not very familiar with ThriftServer. GeoSparkSQL 1.1.0 supports Spark 2.3. Its Maven Coordinate is here: http://datasystemslab.github.io/GeoSpark/news/GeoSpark-All-Modules-Maven-Central-Coordinates/

**Comment by sasoria** [comment]
Yes, I'll  give it a try and report back with my result. ThriftServer2 essentially opens up an odbc/jdbc connection for BI integration.

**Comment by sasoria** [comment]
@jiayuasu I've made a small spark-app in scala using Spark 2.3 and GeoSparkSQL 1.1.0. The queries I've listed initially are working fine.

```sql
select * from pointdf where ST_Contains(ST_PolygonFromEnvelope(1.0,100.0,1000.0,1100.0), pointdf.pointshape));
```

results in:

```
+---------------------------------+--+
|           pointshape               |
+---------------------------------+--+
| POINT (1.1 101.1)	myPointId     |
| POINT (2.1 102.1)	myPointId     |
| POINT (3.1 103.1)	myPointId     |
| POINT (4.1 104.1)	myPointId     |
| POINT (5.1 105.1)	myPointId     |
| POINT (6.1 106.1)	myPointId     |
| POINT (7.1 107.1)	myPointId     |
| POINT (8.1 108.1)	myPointId     |
| POINT (9.1 109.1)	myPointId     |
...
```

**Comment by jiayuasu** [comment]
@sasoria Thanks a lot for verifying this!
