### ISSUE TITLE
Can't generate PolygonRDD

### ISSUE THREAD

**Issue by eleite77** [DataSystemsLab/GeoSpark#271]
## Expected behavior
PolygonRDD should return a valide objet in order to be able to visualize it with yScatterPlot.Visualize(sparkSession.sparkContext, spatialRDD)
## Actual behavior
java.lang.NumberFormatException: For input string: "POLYGON 
## Steps to reproduce the problem
 val USMainLandBoundary = new Envelope(xxx)
    val myScatterPlot = new ScatterPlot(xxxx)
    val spatialRDD = new PolygonRDD(sparkSession.sparkContext, PolygonInputLocation, FileDataSplitter.TSV, false,4)
## Settings

GeoSpark version = 1.1.3

Apache Spark version = 2.3.1

JRE version = 1.8

API type = Scala or Java? Scala

Hi 
I am trying to visualise a spatialRDD in a map.
I am able to run spatial queries but can't generate at the end the spatialRDD

here is my code
    val USMainLandBoundary = new Envelope(-113.79,-109.73,32.99,35.08)
    val myScatterPlot = new ScatterPlot(500, 500,USMainLandBoundary, false)
    val spatialRDD = new PolygonRDD(sparkSession.sparkContext, PolygonInputLocation, FileDataSplitter.TSV, false,4)
    val mapTileRDD = myScatterPlot.Visualize(sparkSession.sparkContext, spatialRDD)

18/09/05 22:04:53 ERROR Executor: Exception in task 0.0 in stage 7.0 (TID 7)
java.lang.NumberFormatException: For input string: "POLYGON ((48.631348 2.780584,48.629655 2.820165,48.629655 2.820165,48.631348 2.780584))"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at org.datasyslab.geospark.formatMapper.FormatMapper.readCoordinates(FormatMapper.java:239)
	at org.datasyslab.geospark.formatMapper.FormatMapper.readGeometry(FormatMapper.java:291)
	at org.datasyslab.geospark.formatMapper.PolygonFormatMapper.call(PolygonFormatMapper.java:78)
	at org.datasyslab.geospark.formatMapper.PolygonFormatMapper.call(PolygonFormatMapper.java:41)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:153)
[...]

it seems to have a problem in my polygon format
could anyone help me because it is difficult to find some examples
thanks

**Comment by eleite77** [comment]
Ok i found the issue. I was not using the good file format for the spatialRDD
thanks

**Comment by AntreasPetsas** [comment]
Hello there @eleite77 . Do you manage to plot range queries? If yes, can you please show me some code? :)
