### ISSUE TITLE
GeoSparkSQL from spark-shell unavailable (Spark 2.2.0)

### ISSUE THREAD

**Issue by Imbruced** [DataSystemsLab/GeoSpark#325]
## Expected behavior
GeoSparkSQL is available via spark-shell.

## Actual behavior
```java
java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.analysis.FunctionRegistry.createOrReplaceTempFunction(Ljava/lang/String;Lscala/Function1;)V
  at org.datasyslab.geosparksql.UDF.UdfRegistrator$$anonfun$registerAll$1.apply(UdfRegistrator.scala:38)
  at org.datasyslab.geosparksql.UDF.UdfRegistrator$$anonfun$registerAll$1.apply(UdfRegistrator.scala:38)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.datasyslab.geosparksql.UDF.UdfRegistrator$.registerAll(UdfRegistrator.scala:38)
  at org.datasyslab.geosparksql.utils.GeoSparkSQLRegistrator$.registerAll(GeoSparkSQLRegistrator.scala:43)
  ... 50 elided
```
## Steps to reproduce the problem
```bash
spark-shell --packages org.datasyslab:geospark:1.1.3,org.datasyslab:geospark-sql_2.2:1.1.3,org.datasyslab:geospark-viz:1.1.3 --conf spark.serializer=org.apache.spark.serializer.KryoSerializer --conf spark.kryo.registrator=org.datasyslab.geosparkviz.core.Serde.GeoSparkVizKryoRegistrator --deploy-mode client
```

```scala
import org.datasyslab.geosparksql.utils._
GeoSparkSQLRegistrator.registerAll(spark)
```
## Settings

GeoSpark version = 1.1.3

Apache Spark version = 2.2.0

JRE version = 1.8.0

API type = Scala 

Scala verison = 2.11.8

**Comment by jiayuasu** [comment]
@Imbruced GeoSpark is available via Spark-shell. Your error seems to be a version-mismatch. Make sure your Spark version is consistent with GeoSpark version
