### ISSUE TITLE
Unable to read polygons from text file

### ISSUE THREAD

**Issue by viswanatharv** [DataSystemsLab/GeoSpark#351]
Hi,

Trying to run the below mentioned script. This code is the part of [**adapterTestScala.scala**](https://github.com/DataSystemsLab/GeoSpark/blob/master/sql/src/test/scala/org/datasyslab/geosparksql/adapterTestScala.scala). It is throwing the error while reading county_small.tsv file. Below are the error details. Please let me know what format I need to use for polygons. The polygon [**county_small.tsv**](https://github.com/DataSystemsLab/GeoSpark/blob/master/sql/src/test/resources/county_small.tsv) and point [**arealm.csv**](https://github.com/DataSystemsLab/GeoSpark/blob/master/sql/src/test/resources/arealm.csv) are from the github location (the links will open the raw files). Still not tested the points file.

```scala
import com.vividsolutions.jts.geom.Geometry
import org.apache.spark.sql.SparkSession
import org.datasyslab.geospark.enums.{FileDataSplitter, GridType, IndexType}
import org.datasyslab.geospark.formatMapper.shapefileParser.ShapefileReader
import org.datasyslab.geospark.spatialOperator.JoinQuery
import org.datasyslab.geospark.spatialRDD.{CircleRDD, PolygonRDD, SpatialRDD}
import org.datasyslab.geosparksql.utils.Adapter
import org.datasyslab.geosparksql.utils.GeoSparkSQLRegistrator

object GeoSparkDFTesting {
  def main(args: Array[String]): Unit = {
    val sparkSession: SparkSession = SparkSession
      .builder()
      .config("spark.driver.memory", "1g")
      .config("spark.executor.memory", "512m")
      .config("spark.hadoop.mapreduce.fileoutputcommitter.algorithm.version", "2")
      .config("spark.shuffle.service.enabled", "true")
      .master("local[*]")
      .appName("Core Process")
      .getOrCreate()

    GeoSparkSQLRegistrator.registerAll(sparkSession)
    sparkSession.udf.register("ST_GeomFromWKT", org.apache.spark.sql.geosparksql.expressions.ST_GeomFromWKT)
    sparkSession.udf.register("ST_Point", org.apache.spark.sql.geosparksql.expressions.ST_Point)
    val mixedWktGeometryInputLocation = "/data/county_small.tsv"
    val polygonWktDf = sparkSession.read.format("csv").option("delimiter", "\t").option("header", "false").load(mixedWktGeometryInputLocation)
    polygonWktDf.createOrReplaceTempView("polygontable")
    val polygonDf = sparkSession.sql("select ST_GeomFromWKT(polygontable._c0) as usacounty, 'abc' as abc, 'def' as def from polygontable")
    val polygonRDD = new SpatialRDD[Geometry]
    polygonRDD.rawSpatialRDD = Adapter.toRdd(polygonDf)
    polygonRDD.analyze()

    val arealmPointInputLocation = "/data/arealm.csv"
    val pointCsvDF = sparkSession.read.format("csv").option("delimiter", ",").option("header", "false").load(arealmPointInputLocation)
    pointCsvDF.createOrReplaceTempView("pointtable")
    val pointDf = sparkSession.sql("select ST_Point(cast(pointtable._c0 as Decimal(24,20)),cast(pointtable._c1 as Decimal(24,20))) as arealandmark from pointtable")
    val pointRDD = Adapter.toSpatialRdd(pointDf, "arealandmark")
    pointRDD.analyze()

    pointRDD.spatialPartitioning(GridType.QUADTREE)
    polygonRDD.spatialPartitioning(pointRDD.getPartitioner)

    pointRDD.buildIndex(IndexType.QUADTREE, true)

    val joinResultPairRDD = JoinQuery.SpatialJoinQueryFlat(pointRDD, polygonRDD, true, true)

    val joinResultDf = Adapter.toDf(joinResultPairRDD, sparkSession)
    joinResultDf.show()

    val joinResultDf2 = Adapter.toDf(joinResultPairRDD, List("abc", "def"), List(), sparkSession)
    joinResultDf2.show()
  }
}
```

Thanks
Vish

## Error Details
```scala
Exception in thread "main" org.apache.spark.sql.AnalysisException: cannot resolve 'UDF:ST_GeomFromWKT(_c0)' due to data type mismatch: argument 1 requires array<struct<>> type, however, 'polygontable.`_c0`' is of string type.; line 1 pos 7;
'Project [UDF:ST_GeomFromWKT(_c0#10) AS usacounty#46, abc AS abc#47, def AS def#48]
+- SubqueryAlias `polygontable`
   +- Relation[_c0#10,_c1#11,_c2#12,_c3#13,_c4#14,_c5#15,_c6#16,_c7#17,_c8#18,_c9#19,_c10#20,_c11#21,_c12#22,_c13#23,_c14#24,_c15#25,_c16#26,_c17#27] csv

	at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$3.applyOrElse(CheckAnalysis.scala:115)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$3.applyOrElse(CheckAnalysis.scala:107)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:278)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:278)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:277)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:275)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:275)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:326)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapChildren(TreeNode.scala:324)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:275)
	at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$transformExpressionsUp$1.apply(QueryPlan.scala:93)
	at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$transformExpressionsUp$1.apply(QueryPlan.scala:93)
	at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$1.apply(QueryPlan.scala:105)
	at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$1.apply(QueryPlan.scala:105)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpression$1(QueryPlan.scala:104)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1(QueryPlan.scala:116)
	at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1$2.apply(QueryPlan.scala:121)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$1(QueryPlan.scala:121)
	at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$2.apply(QueryPlan.scala:126)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:187)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.mapExpressions(QueryPlan.scala:126)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionsUp(QueryPlan.scala:93)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:107)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:85)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:127)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$class.checkAnalysis(CheckAnalysis.scala:85)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:95)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$$anonfun$executeAndCheck$1.apply(Analyzer.scala:108)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$$anonfun$executeAndCheck$1.apply(Analyzer.scala:105)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:201)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:105)
	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:57)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:55)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:47)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:79)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:642)
	at GeoSparkDFTesting$.main(GeoSparkDFTesting.scala:28)
	at GeoSparkDFTesting.main(GeoSparkDFTesting.scala)
```

## Expected behavior
Need to read the polygon file

## Actual behavior
Throwing error while reading a file

## Settings

GeoSpark version = 1.2.0-SNAPSHOT

Apache Spark version = 2.4.0

JRE version = 1.8?

API type = Scala

**Comment by jiayuasu** [comment]
@viswanatharv The first mistake I noticed is that you shouldn't use the following line

```
sparkSession.udf.register("ST_GeomFromWKT", org.apache.spark.sql.geosparksql.expressions.ST_GeomFromWKT)
sparkSession.udf.register("ST_Point", org.apache.spark.sql.geosparksql.expressions.ST_Point)
```

GeoSparkSQL.registerAll has already registered all GeoSpark expressions.

**Comment by viswanatharv** [comment]
@jiayuasu 

After removing the functions, it is working fine. Thanks for the update.

Thanks
Vish...
