### ISSUE TITLE
Classpath issue when integrating sparkviz with s3

### ISSUE THREAD

**Issue by eschizoid** [DataSystemsLab/GeoSpark#378]
## Expected behavior
`geospark_viz` should be pulling (transitively)`com.amazonaws:aws-java-sdk:1.7.4` instead of `com.amazonaws:aws-java-sdk-core:1.11.160`

## Actual behavior
`geospark_viz` is shading the class `AmazonHttpClient` from `com.amazonaws:aws-java-sdk-core:1.11.160`. This is causing problems when spark integrates with s3 since spark 2.4.x requires  
` com.amazonaws:aws-java-sdk:1.7.4`

## Steps to reproduce the problem
Execute any spark job from Zeppelin UI that reads/writes data from s3 and also has `geospark_viz` as a dependency

```
java.lang.NoSuchMethodError: com.amazonaws.http.AmazonHttpClient.disableStrictHostnameVerification()V
  at com.amazonaws.services.s3.AmazonS3Client.init(AmazonS3Client.java:444)
  at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:391)
  at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:371)
  at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:235)
  at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2669)
  at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
  at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
  at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
  at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
  at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
  at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:45)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:332)
  at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
  ... 45 elided
```

## Settings

GeoSpark version = 2.3

Apache Spark version = 2.4.3

JRE version = 1.8?
1.8

API type = Scala or Java?
Scala

**Comment by eschizoid** [comment]
Please see #379 and let me know what you think
