### ISSUE TITLE
ST_Point results in ClassNotFoundException ..CodegenFallback$class

### ISSUE THREAD

**Issue by heaven00** [DataSystemsLab/GeoSpark#380]
I am running 
```
val observationsDf = sparkSession.read.parquet(filePath)
  .createTempView("observations")

sparkSession.sql(s"""SELECT ST_Point(cast(observations.locationlon as Decimal(24, 20)),
       |cast(observations.locationlat as Decimal(24, 20))) as geometry
       |from observations""".stripMargin)
```
observations is a parquet file containing 
```
{"idvalue":123,"locationlat":51.2555051,"locationlon":-0.746097,"locationaccuracyhorizontal":2}
{"idvalue":123,"locationlat":51.2555052,"locationlon":-0.7460979999999999,"locationaccuracyhorizontal":2}
{"idvalue":123,"locationlat":51.2555054,"locationlon":-0.746099,"locationaccuracyhorizontal":2}
{"idvalue":123,"locationlat":51.2555059,"locationlon":-0.746097,"locationaccuracyhorizontal":2}
{"idvalue":124,"locationlat":51.2556,"locationlon":-1.1,"locationaccuracyhorizontal":2}
```

## Expected behavior
I expect to get a dataframe with column `geometry` with `points geometry`

## Actual behavior
```
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/apache/spark/sql/catalyst/expressions/codegen/CodegenFallback$class
 at java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.util.concurrent.FutureTask.get(FutureTask.java:192)
  at org.scalatest.tools.ConcurrentDistributor.waitUntilDone(ConcurrentDistributor.scala:50)  at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1334)
 at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1033)
 at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1011)
 at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1509)
[31m  at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1011)[0m
[31m  at org.scalatest.tools.Runner$.main(Runner.scala:827)[0m
[31m  at org.scalatest.tools.Runner.main(Runner.scala)[0m
[31m  ...[0m
[31m  Cause: java.lang.NoClassDefFoundError: org/apache/spark/sql/catalyst/expressions/codegen/CodegenFallback$class[0m
[31m  at org.apache.spark.sql.geosparksql.expressions.ST_Point.<init>(Constructors.scala:223)[0m
[31m  at org.apache.spark.sql.geosparksql.expressions.ST_Point$.apply(Constructors.scala:222)[0m
[31m  at org.apache.spark.sql.geosparksql.expressions.ST_Point$.apply(Constructors.scala:222)[0m
[31m  at org.apache.spark.sql.catalyst.analysis.SimpleFunctionRegistry.lookupFunction(FunctionRegistry.scala:115)[0m
[31m  at org.apache.spark.sql.catalyst.catalog.SessionCatalog.lookupFunction(SessionCatalog.scala:1273)[0m
[31m  at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveFunctions$$anonfun$apply$13$$anonfun$applyOrElse$143.$anonfun$applyOrElse$66(Analyzer.scala:1329)[0m
[31m  at org.apache.spark.sql.catalyst.analysis.package$.withPosition(package.scala:53)[0m
[31m  at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveFunctions$$anonfun$apply$13$$anonfun$applyOrElse$143.applyOrElse(Analyzer.scala:1329)[0m
[31m  at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveFunctions$$anonfun$apply$13$$anonfun$applyOrElse$143.applyOrElse(Analyzer.scala:1312)[0m
[31m  at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDown$1(TreeNode.scala:256)[0m
[31m  ...[0m
[31m  Cause: java.lang.ClassNotFoundException: org.apache.spark.sql.catalyst.expressions.codegen.CodegenFallback$class[0m
[31m  at java.net.URLClassLoader.findClass(URLClassLoader.java:382)[0m
[31m  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)[0m
[31m  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)[0m
[31m  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)[0m
[31m  at org.apache.spark.sql.geosparksql.expressions.ST_Point.<init>(Constructors.scala:223)[0m
[31m  at org.apache.spark.sql.geosparksql.expressions.ST_Point$.apply(Constructors.scala:222)[0m
[31m  at org.apache.spark.sql.geosparksql.expressions.ST_Point$.apply(Constructors.scala:222)[0m
[31m  at org.apache.spark.sql.catalyst.analysis.SimpleFunctionRegistry.lookupFunction(FunctionRegistry.scala:115)[0m
[31m  at org.apache.spark.sql.catalyst.catalog.SessionCatalog.lookupFunction(SessionCatalog.scala:1273)[0m
[31m  at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveFunctions$$anonfun$apply$13$$anonfun$applyOrElse$143.$anonfun$applyOrElse$66(Analyzer.scala:1329)[0m
[31m  ...[0m
```

## Settings
```
new SparkConf().setAppName("test-conf")
    .setMaster("local")
    .set("spark.serializer", classOf[KryoSerializer].getName)
    .set("spark.kryo.registrator", classOf[GeoSparkKryoRegistrator].getName)
```

GeoSpark version = 1.2.0
```
implementation group: 'org.datasyslab', name: 'geospark', version: 1.2.0
implementation group: 'org.datasyslab', name: 'geospark-sql_2.3', version: 1.2.0
```

Apache Spark version = 2.4.0

JRE version = openJDK 8

API type = Scala

**Comment by heaven00** [comment]
![image](https://user-images.githubusercontent.com/1822197/62927684-aa562700-bdd4-11e9-8c3a-b8108b9dfe29.png)

Sorry I have spent too much of my time on this and I am new to scala

**Comment by jiayuasu** [comment]
@heaven00 Sorry man. I am late. I was super busy recently. I have tried GeoSpark on Spark 2.4.0 and it works fine. And according to your errors, it doesn't seem to be a GeoSpark related issue. Can you try GeoSpark template project instead? https://datasystemslab.github.io/GeoSpark/tutorial/GeoSpark-Runnable-DEMO/

**Comment by heaven00** [comment]
Hey, no worries I am also trying to understand why this error is coming. So far where I am at is that for some weird reason gradle is not picking up codegen fallback class during runtime. 

From what I have read, its mainly due to version mismatches. Sadly I can't change Scala version or things because there is already code in the project that's running on it.

P.S. I did try running the template it gave even more different and weird errors and most us are sort of lost on this one. I might just try to use py spark and some hack to run this.

**Comment by jiayuasu** [comment]
If this is caused by Scala version issue of GeoSpark (GeoSpark is compiled in Scala 2.11), you can clone GeoSpark repo and simply change these two lines to Scala 2.12 version:
https://github.com/DataSystemsLab/GeoSpark/blob/master/pom.xml#L46
Then either (1) copy-paste the GeoSpark source code in your own code
or (2) run "mvn clean install -DskipTests" in your terminal and get the compiled jars.

This is fairly simply.

**Comment by heaven00** [comment]
I got it working with the GeosparkTemplate configuration in a different sbt project with scala version `2.11.11` and `2.12.8` 

This seems like some problem with the gradle setting we have in our project

**Comment by heaven00** [comment]
Moving to `2.11` scalaVersion fixed this issue for us.
