### ISSUE TITLE
Conflicting property-based creators, JSON LineString mapping

### ISSUE THREAD

**Issue by aldayj-intific** [DataSystemsLab/GeoSpark#58]
I believe the version of com.fasterxml.jackson compiled with geospark is out of date, and carries a bug when reading LineString data from JSON.

`java.lang.RuntimeException: java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Conflicting property-based creators: already had explicitly marked [constructor for org.wololo.geojson.LineString, annotations: {interface com.fasterxml.jackson.annotation.JsonCreator=@com.fasterxml.jackson.annotation.JsonCreator(mode=DEFAULT)}], encountered [constructor for org.wololo.geojson.LineString, annotations: {interface com.fasterxml.jackson.annotation.JsonCreator=@com.fasterxml.jackson.annotation.JsonCreator(mode=DEFAULT)}]
        at GeoExample$CustomGeoJsonMapper.call(GeoExample.java:262)
        at GeoExample$CustomGeoJsonMapper.call(GeoExample.java:232)
        at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$1$1.apply(JavaRDDLike.scala:125)
        at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$1$1.apply(JavaRDDLike.scala:125)
        at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
        at org.apache.spark.rdd.RDD$$anonfun$reduce$1$$anonfun$15.apply(RDD.scala:1010)
        at org.apache.spark.rdd.RDD$$anonfun$reduce$1$$anonfun$15.apply(RDD.scala:1009)
        at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:1980)
        at org.apache.spark.SparkContext$$anonfun$33.apply(SparkContext.scala:1980)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)`

Please refer to [Conflicting property-based creators #8](https://github.com/bjornharrtell/jts2geojson/issues/8). You may just need update the version you are using.

This is when GeoJSONFactory.create(String json) is used. I didn't think it to be a geospark issue, but seeing as how this issue has been resolved already in the main package, it must mean that geospark is carrying an older version that introduces the bug.

**Comment by aldayj-intific** [comment]
Hey @jiayuasu , I worked out an easy fix for this. You'll only need to update jts2geojson from 0.7.0 to 0.10.0 in the pom.xml and that should fix this issue. I'm using a local build of it to get by, but it would be awesome if you can get this updated in maven.

**Comment by jiayuasu** [comment]
Hi @aldayj-intific ,

I have updated the dependency and have published GeoSpark 0.5.2 snapshot onto Maven Central. It should be synced to Maven Central within several hours. Check out the coordinates here: https://github.com/DataSystemsLab/GeoSpark/wiki/GeoSpark-Maven-Central-Coordinates

**Comment by aldayj-intific** [comment]
@jiayuasu Awesome,

Thanks for the quick update on this!

**Comment by aldayj-intific** [comment]
Confirmed new update, everything is green!
